name: Flutter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'push' && 'production' || 'staging' }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ vars.JAVA_VERSION }}
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ vars.FLUTTER_CHANNEL }}
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          cache: true
      - name: Verify Flutter instalation
        run: flutter doctor -v
      - name: Fetch dependencies
        run: flutter pub get
      - name: Build release version
        env:
          API_AUTHORITY: ${{ vars.API_AUTHORITY }}
        run: flutter build apk --release --dart-define=API_AUTHORITY=$API_AUTHORITY
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ vars.ARTIFACT_PREFIX }}
          path: build/app/outputs/flutter-apk
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ vars.FLUTTER_CHANNEL }}
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          cache: true
      - name: Fetch dependencies
        run: flutter pub get
      - name: Run the Dart and Flutter analyzer
        run: flutter analyze
      - name: Ensure the Dart code is formatted correctly
        run: dart format --set-exit-if-changed --output none .
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    if: false
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ vars.FLUTTER_CHANNEL }}
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          cache: true
      - name: Fetch dependencies
        run: flutter pub get
      - name: Run unit tests
        run: flutter test
